inherit_gem:
  decidim-dev: rubocop-decidim.yml

AllCops:
  Exclude:
    - 'db/**/*.rb'
    - 'development_app/**/**/*.rb'
    - 'development_app/Gemfile'
    - 'vendor/**/*'
    - "spec/decidim_dummy_app*/**/*"

Rails/FilePath:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false
